name: Bug Report
description: Report broken or incorrect behaviour
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out a bug.

        Please note that this form is for bugs only!
  - type: input
    attributes:
      label: Summary
      description: A simple summary of your bug report
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: >
         What you did to make it happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Results
      description: >
        What actually happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Pictures and Screenshots
      description: Add pictures and screenshots if you can
    validations:
      required : false
  - type: textarea
    attributes:
      label: Additional Context
      description: If there is anything else to say, please do so here.