name: Feature Request
description: Suggest a feature for Grogbot.py
body:
  - type: input
    attributes:
      label: Summary
      description: >
        A short summary of what your feature request is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: The Problem
      description: >
        What problem is your feature trying to solve or help?
    validations:
      required: true
  - type: textarea
    attributes:
      label: The Ideal Solution
      description: >
        What is your ideal solution to the problem? (Answer if this is for fixing something)
        What would you like this feature to do?
        What is your way of solving the problem or adding the feature
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: If there is anything else to say, please do so here.